/*
 * Created on 3 nov. 2014 ( Time 12:06:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.bean;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "Participant" ( stored in table "PARTICIPANT" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ParticipantKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="PARTICIPANT_EVENT_ID", nullable=false)
    private Integer    participantEventId ;
    
    @Column(name="PARTICIPANT_CUSTOMER_ID", nullable=false)
    private Integer    participantCustomerId ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ParticipantKey() {
        super();
    }

    public ParticipantKey( Integer participantEventId, Integer participantCustomerId ) {
        super();
        this.participantEventId = participantEventId ;
        this.participantCustomerId = participantCustomerId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setParticipantEventId( Integer value ) {
        this.participantEventId = value;
    }
    public Integer getParticipantEventId() {
        return this.participantEventId;
    }

    public void setParticipantCustomerId( Integer value ) {
        this.participantCustomerId = value;
    }
    public Integer getParticipantCustomerId() {
        return this.participantCustomerId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ParticipantKey other = (ParticipantKey) obj; 
		//--- Attribute participantEventId
		if ( participantEventId == null ) { 
			if ( other.participantEventId != null ) 
				return false ; 
		} else if ( ! participantEventId.equals(other.participantEventId) ) 
			return false ; 
		//--- Attribute participantCustomerId
		if ( participantCustomerId == null ) { 
			if ( other.participantCustomerId != null ) 
				return false ; 
		} else if ( ! participantCustomerId.equals(other.participantCustomerId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute participantEventId
		result = prime * result + ((participantEventId == null) ? 0 : participantEventId.hashCode() ) ; 
		//--- Attribute participantCustomerId
		result = prime * result + ((participantCustomerId == null) ? 0 : participantCustomerId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(participantEventId); 
		sb.append("|"); 
		sb.append(participantCustomerId); 
        return sb.toString();
    }
}
