/*
 * Created on 28 oct. 2014 ( Time 22:18:22 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.test.persistence;


import fr.emn.eventmanager.bean.Event;
import fr.emn.eventmanager.mock.EventMock;
import fr.emn.eventmanager.persistence.PersistenceServiceProvider;
import fr.emn.eventmanager.persistence.service.EventPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Event persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class EventPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		EventPersistence service = PersistenceServiceProvider.getService(EventPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Event persistence : delete + load ..." );
		
		EventPersistence service = PersistenceServiceProvider.getService(EventPersistence.class);
		
		EventMock mock = new EventMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(EventPersistence service, EventMock mock, String eventId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Event entity = service.load( eventId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( eventId ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( eventId );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
