/*
 * Created on 3 nov. 2014 ( Time 14:40:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.test.persistence;


import fr.emn.eventmanager.bean.Participant;
import fr.emn.eventmanager.mock.ParticipantMock;
import fr.emn.eventmanager.persistence.PersistenceServiceProvider;
import fr.emn.eventmanager.persistence.service.ParticipantPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Participant persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParticipantPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ParticipantPersistence service = PersistenceServiceProvider.getService(ParticipantPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Participant persistence : delete + load ..." );
		
		ParticipantPersistence service = PersistenceServiceProvider.getService(ParticipantPersistence.class);
		
		ParticipantMock mock = new ParticipantMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(ParticipantPersistence service, ParticipantMock mock, Integer participantEventId, Integer participantCustomerId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Participant entity = service.load( participantEventId, participantCustomerId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( participantEventId, participantCustomerId ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( participantEventId, participantCustomerId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
