
/*
 * Created on 28 oct. 2014 ( Time 22:18:22 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.mock;

import java.util.LinkedList;
import java.util.List;

import fr.emn.eventmanager.bean.Customer;
import fr.emn.eventmanager.mock.tool.MockValues;

public class CustomerMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Customer createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Customer createInstance( Long customerId ) {
		Customer entity = new Customer();
		// Init Primary Key fields
		entity.setCustomerId( customerId) ;
		// Init Data fields
		entity.setCustomerEmail( mockValues.nextString(254) ) ; // java.lang.String 
		entity.setCustomerPassword( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setCustomerFirstname( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCustomerLastname( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCustomerCompany( mockValues.nextString(50) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEvent( TODO ) ; // List<Event> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Customer> createList(int count) {
		List<Customer> list = new LinkedList<Customer>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
