
/*
 * Created on 28 oct. 2014 ( Time 22:18:22 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.mock;

import java.util.LinkedList;
import java.util.List;

import fr.emn.eventmanager.bean.Participant;
import fr.emn.eventmanager.mock.tool.MockValues;

public class ParticipantMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Participant createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(32), mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Participant createInstance( String participantEventId, Long participantCustomerId ) {
		Participant entity = new Participant();
		// Init Primary Key fields
		entity.setParticipantEventId( participantEventId) ;
		entity.setParticipantCustomerId( participantCustomerId) ;
		// Init Data fields
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Participant> createList(int count) {
		List<Participant> list = new LinkedList<Participant>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
