/*
 * Created on 3 nov. 2014 ( Time 14:40:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.emn.eventmanager.persistence.service;

import java.util.List;
import java.util.Map;

import fr.emn.eventmanager.bean.Customer;

/**
 * Basic persistence operations for entity "Customer"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface CustomerPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param customer
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Customer customer) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param customerId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer customerId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param customer
	 */
	public void insert(Customer customer) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param customerId
	 * @return the entity loaded (or null if not found)
	 */
	public Customer load(Integer customerId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Customer> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Customer> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Customer> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param customer
	 * @return
	 */
	public Customer save(Customer customer) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Customer> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
